name: moonstone
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - scipy
  - numba
  - dask
  - distributed
  - h5py
  - pyyaml
  - pytest
  - pip:
    - -r backend/requirements.txt
    - einsteinpy
    - aiohttp
    - requests
    - pandas
    - xarray
    - scikit-learn
